import PostList from "@/components/post-list";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function WritingLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className="flex items-center w-full h-full">
            <PostList />
            <div className="h-full w-full">
                {children}
            </div>
        </div>
    );
}
